SELECT SHIPS.NAME, CLASSES.COUNTRY, CLASSES.NUMGUNS, SHIPS.LAUNCHED
    FROM SHIPS
    INNER JOIN CLASSES
        ON SHIPS.CLASS = CLASSES.CLASS
        AND SHIPS.NAME IN (SELECT CLASS
                            FROM CLASSES
                            WHERE CLASSES.CLASS NOT IN (SELECT CLASS FROM SHIPS));