# Generated by Django 2.2.1 on 2019-05-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hack Plane', max_length=200)),
                ('capacity', models.IntegerField()),
                ('crew', models.IntegerField()),
            ],
        ),
    ]
