# Generated by Django 2.2.1 on 2019-05-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='name',
            field=models.CharField(default='Hack Plane', max_length=200, unique=True),
        ),
    ]
