# Generated by Django 2.2.1 on 2019-05-29 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Planes', '0002_auto_20190523_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('passengers', models.IntegerField()),
                ('max_passengers', models.IntegerField()),
                ('from_dest', models.CharField(max_length=100)),
                ('to_dest', models.CharField(max_length=100)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='Planes.Plane')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
